### ISSUE TITLE
Problem of run sample_bashs

### ISSUE THREAD

**Issue by doubleZ0108** [xxlong0/SparseNeuS#36]
Hi, thanks for your work.
When I run `sample_bashs` for an easy test, I got the following errors:
```
pyparsing.exceptions.ParseException: Expected '}', found '='  (at char 1374), (line:67, col:16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp_runner_finetune.py", line 608, in <module>
    clip_wh=[int(x) for x in args.clip_wh]
  File "exp_runner_finetune.py", line 58, in __init__
    self.conf = ConfigFactory.parse_file(conf_path)
  File "/home/pai/lib/python3.6/site-packages/pyhocon/config_parser.py", line 142, in parse_file
    return cls.parse_string(content, os.path.dirname(filename), resolve, unresolved_value)
  File "/home/pai/lib/python3.6/site-packages/pyhocon/config_parser.py", line 192, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/home/pai/lib/python3.6/site-packages/pyhocon/config_parser.py", line 455, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/home/pai/lib/python3.6/site-packages/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseSyntaxException: Expected '}', found '='  (at char 1374), (line:67, col:16)
```

I am new in Neus and I just want to have a try, so how can I correct it and have a test?
Thanks for your reply.

**Comment by doubleZ0108** [comment]
I have fixed the bugs after adding `,` at the end of #67 and #68 of `confs/finetune.conf`.
Like
```
model {
  finetune_lod = 1,
  h_patch_size = 3,

  ...
}
```

Maybe different versions of dependencies have different implementations when parsing configure files.
